Repository jenkins-x/jx-helpers, pull requests merged in 2020-12, with the labels that each got.

#97 refactor: remove old v2 code
  Makefile
  go.mod
  go.sum
  hack/upload_plugin.sh
  pkg/cobras/templates/command_groups.go
  pkg/cobras/templates/helpers.go
  pkg/extensions/config.go
  pkg/extensions/definitions.go
  pkg/extensions/execution.go
  pkg/extensions/management.go
  pkg/extensions/platforms.go
  pkg/extensions/plugins.go
  pkg/extensions/plugins_test.go
  pkg/gitclient/helpers.go
  pkg/gitclient/setup.go
  pkg/helmer/helpers.go
  pkg/kube/activities/activity.go
  pkg/kube/activities/activity_functions.go
  pkg/kube/activities/activity_test.go
  pkg/kube/activities/field_map.go
  pkg/kube/activities/field_map_test.go
  pkg/kube/activities/update_status.go
  pkg/kube/activities/update_status_test.go
  pkg/kube/jxclient/jxclient.go
  pkg/kube/jxenv/env.go
  pkg/kube/jxenv/env_test.go
  pkg/kube/jxenv/namespaces.go
  pkg/kube/jxenv/namespaces_test.go
  pkg/scmhelpers/discover.go
  pkg/scmhelpers/discover_test.go
  pkg/scmhelpers/helpers.go
  pkg/testhelpers/testjx/repository.go
  pkg/versionstream/version_data.go
  pkg/versionstream/versionstreamrepo/gitrepo.go
  pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go
Labels: approved, size/XXL

#104 refactor: move traditional CRDs back to jenkins.io group so we dont need to create new CRDs
  go.mod
  go.sum
  pkg/cobras/templates/command_groups.go
  pkg/cobras/templates/helpers.go
  pkg/extensions/platforms.go
  pkg/extensions/plugins.go
  pkg/extensions/plugins_test.go
  pkg/kube/activities/activity.go
  pkg/kube/activities/activity_functions.go
  pkg/kube/activities/activity_test.go
  pkg/kube/activities/field_map.go
  pkg/kube/activities/field_map_test.go
  pkg/kube/activities/update_status.go
  pkg/kube/activities/update_status_test.go
  pkg/kube/jxenv/env.go
  pkg/kube/jxenv/env_test.go
  pkg/kube/jxenv/namespaces.go
  pkg/kube/jxenv/namespaces_test.go
  pkg/scmhelpers/helpers.go
  pkg/testhelpers/testjx/repository.go
Labels: approved, size/L

#106 feat: add helper to get cluster requirements from the cluster git repo
  pkg/requirements/requirements.go
Labels: approved, size/M

#114 fix: issue with getting cluster requirements in cluster and private git cluster git repo
  pkg/gitclient/credentialhelper/git_credential.go
  pkg/gitclient/credentialhelper/git_credential_test.go
  pkg/gitclient/credentialhelper/test_data/write_file_from_secret/bar/password
  pkg/gitclient/credentialhelper/test_data/write_file_from_secret/bar/username
  pkg/gitclient/credentialhelper/test_data/write_file_from_secret/expected
  pkg/requirements/requirements.go
Labels: approved, size/L

#115 chore: tidy up error handling
  pkg/gitclient/credentialhelper/git_credential_test.go
  pkg/requirements/requirements.go
Labels: approved, size/S

#124 feat: added in selector exclusion ability to filter
  pkg/cobras/templates/markdown.go
  pkg/helmer/constants.go
  pkg/kyamls/filter.go
  pkg/kyamls/filter_test.go
  pkg/kyamls/test_data/configmap.yaml
  pkg/stringhelpers/strings.go
Labels: approved, lgtm, ok-to-test, size/L
