Repository jenkins-x/jx-helpers, pull requests merged in 2020-10, with the labels that each got.

#56 feat: add some helper functions taken from the old jx v2 codebase
  pkg/kube/jxenv/env.go
  pkg/kube/jxenv/env_test.go
Labels: approved, size/M

#44 Chore: rename git username CLI argument and add information about git credentials
  pkg/scmhelpers/factory.go
Labels: approved, ok-to-test, size/XS

#58 feat: add duck package from knative to help when working with unstructured objects
  go.mod
  go.sum
  pkg/knative_pkg/README.md
  pkg/knative_pkg/duck/interface.go
  pkg/knative_pkg/duck/unstructured.go
  pkg/knative_pkg/kmeta/accessor.go
  pkg/knative_pkg/kmeta/owner_references.go
Labels: approved, size/L

#71 chore: fix blocking sonarcloud issues and a couple of critical ones too
  pkg/boot/boot_secret.go
  pkg/boot/boot_secret_test.go
  pkg/cmdrunner/commands.go
  pkg/cmdrunner/commands_test.go
  pkg/cobras/templates/helpers.go
  pkg/gitclient/credentialhelper/git_credentialhelper_test.go
  pkg/gitclient/loadcreds/loadcreds_test.go
Labels: approved, lgtm, size/L
