Repository jenkins-x/jx-helpers, pull requests merged in 2020-11, with the labels that each got.

#83 feat: added in function to check if kind is a CRD
  pkg/kyamls/helpers.go
Labels: approved, lgtm, ok-to-test, size/XS

#87 chore: lets add an extra function to find git credentials from a specific secret
  pkg/gitclient/loadcreds/loadcreds.go
Labels: approved, size/M

#88 chore: fix logging
  pkg/gitclient/loadcreds/loadcreds.go
Labels: approved, size/XS

#99 feat: added in retrycommand helper for cobra
  pkg/cobras/helper/retry.go
  pkg/cobras/helper/retry_test.go
Labels: approved, lgtm, ok-to-test, size/L
