Repository jenkins-x/jx-helpers, pull requests merged in 2021-02, with the labels that each got.

#30 refactor: return struct instead of interface
  pkg/gitclient/cli/cli_client.go
Labels: ok-to-test, size/XS

#187 chore: fix mistype in logs
  pkg/kube/pods/pod.go
Labels: approved, lgtm, ok-to-test, size/XS

#188 chore: add a funtion to execute a command in a pod
  pkg/kube/pods/pod.go
Labels: approved, size/M
