Repository jenkins-x/jx-helpers, pull requests merged in 2022-11, with the labels that each got.

#390 fix: mask secrets in import logs
  pkg/gitclient/loadcreds/loadcreds.go
  pkg/gitclient/loadcreds/loadcreds_test.go
  pkg/gitclient/loadcreds/testdata/git/credentials
  pkg/gitclient/loadcreds/testdata/git/credentials_missing_pass
Labels: size/S, approved

#392 Updated go version to 1.19 in jx-helpers
  Makefile
  go.mod
Labels: size/XS, approved, ok-to-test

#391 feat: Generify map functions
  .github/workflows/codeql-analysis.yml
  pkg/maps/maps.go
Labels: size/M, approved
