Repository jenkins-x/jx-helpers, pull requests merged in 2022-06, with the labels that each got.

#376 fix(survey v2): set default value as interface instead of string
  go.mod
  pkg/input/batch/batch.go
  pkg/input/fake/fake.go
  pkg/input/interface.go
  pkg/input/survey/survey.go
  pkg/input/survey/survey_test.go
  pkg/scmhelpers/factory.go
Labels: size/L

#377 fix: Deletion of old plugin versions
  OWNERS
  OWNERS_ALIASES
  pkg/cobras/templates/templates.go
  pkg/extensions/plugins.go
Labels: size/S, approved

#375 finding url from istio virtual service
  pkg/kube/services/services.go
  pkg/kube/services/services_test.go
Labels: size/M, approved, ok-to-test

#379 adding http protocol
  pkg/kube/services/services.go
  pkg/kube/services/services_test.go
Labels: size/XS, approved, ok-to-test

#378 feat: Add function EnsureStringArrayContains
  pkg/stringhelpers/strings.go
  pkg/stringhelpers/strings_test.go
Labels: size/S, approved

#380 feat: Add function SparseCloneToDir
  pkg/gitclient/helpers.go
  pkg/input/survey/survey_test.go
  pkg/kube/jxenv/env_test.go
  pkg/kyamls/helpers_test.go
Labels: size/M, approved

#382 chore: upgrade kube-client to 0.3.3
  go.mod
  go.sum
Labels: size/M, approved
