Repository jenkins-x/jx-helpers, pull requests merged in 2023-08, with the labels that each got.

#404 fix: updated order of parameters for sparse-checkout
  pkg/gitclient/helpers.go
Labels: size/XS, approved, ok-to-test

#405 fix: upgradebot config
  .jx/updatebot.yaml
Labels: size/S, approved

#406 fix: upgradebot config
  .jx/updatebot.yaml
Labels: size/XS, approved

#407 feat: support adding only kind or selector part of filter flags
  pkg/kyamls/filter.go
Labels: size/S, approved
